repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.9
    hooks:
    -   id: ruff
        args: [--fix]
    -   id: ruff-format

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-json
    -   id: debug-statements
    -   id: check-added-large-files
        args: ['--maxkb=2000']  # Allow up to 2MB for lock files

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.1
    hooks:
    -   id: mypy
        additional_dependencies:
            - types-requests>=2.31.0
            - types-PyYAML>=6.0.12.11
            - types-aiofiles>=24.1.0.20250708
            - types-aioboto3
            - types-python-jose>=3.5.0.20250531
            - aioboto3
            - moto[s3]
        exclude: ^(docs/|example-plugin/|tests/fixtures|server/tests/)
