name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          # - macos-latest # ignore for now
          # - windows-latest # ignore for now
    steps:
    - uses: actions/checkout@v4

    - name: Set up Pixi
      uses: prefix-dev/setup-pixi@v0.8.3
      with:
        environments: test lint
        cache: true

    - name: Run linting and format checks
      run: pixi run -e lint lint

    - name: Run tests with coverage
      run: pixi run -e test test

    - name: Check code formatting
      run: pixi run -e lint check
