name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          # - macos-latest # ignore for now
          # - windows-latest # ignore for now
        python-version:
          - '3.11'
          # - '3.12' # conflicts with env.yml python=3.11
          # - '3.13' # doesn't work yet
    steps:
    - uses: actions/checkout@v3

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: ${{ matrix.python-version }}
        environment-file: server/env.yml
        activate-environment: ftw-inference-api

    - name: Install pre-commit
      run: pip install pre-commit
      shell: bash -el {0}

    - name: Download model(s)
      run: |
        mkdir -p server/data/models
        curl -L -o server/data/models/2_Class_FULL_FTW_Pretrained.ckpt https://github.com/fieldsoftheworld/ftw-baselines/releases/download/v1/2_Class_FULL_FTW_Pretrained.ckpt

    - name: Lint and format check with pre-commit
      uses: pre-commit/action@v3.0.0

    - name: Run tests
      run: |
        cd server
        pytest -v --cov=server
      shell: bash -el {0}
